name = "moon-comments"
main = "src/index.js"
compatibility_date = "2023-08-23"
workers_dev = true

[[d1_databases]]
binding = "DATABASE"
database_id = "c5b0798d-3302-4819-b634-98c7afc6e907"
database_name = "moon-comments-db"
